---

- name: Installing Vim Packages
  apt: pkg={{ item }} state=latest update_cache={{ update_cache }} cache_valid_time={{ cache_valid_time }}
  with_items:
    - vim
    - exuberant-ctags
    - ncurses-term
  tags:
    - vim:install
